### PR TITLE
change the colors of overlay and badge

### PR DESCRIPTION
**Pull request by der-john**
Our meinberlin POs alerted us to the fact that the colors of badges and overlays are not easily readible. That's why we're changing it for adhocracy3.

### CODE REVIEW

**Comment by xi** [comment]
-  We should definitely add contrast checks to this pull request to make sure that these changes are actually sufficient.
-  You adapted the function colors in core, but they are typically overwritten in many projects. Please also adapt the overwrites.

**Comment by xi** [comment]
I talked to @nicoladimarco and he will look into the colors again tomorrow.

**Comment by der-john** [comment]
> You replaced color-function-neutral by color-function-informative in one place.

I can't see where.

**Comment by der-john** [comment]
has been rebased.

**Pull request closed without merging**
