### PR TITLE
rm traces of address from frontend

### PR DESCRIPTION
**Pull request by xi**
*see #1546*

is not used in the UI anyway and is up for deprecation in the backend.

### CODE REVIEW

**Comment by nidico** [comment]
The typescript does not build.

**Comment by xi** [comment]
> The typescript does not build.

It seems like address is required in the backend. So this is on hold until the backend has been fixed.

**Comment by xi** [comment]
Could someone please review this? @pallix?

**Comment by pallix** [comment]
@joka don't we need a migration?

**Comment by joka** [comment]
> @joka don't we need a migration?

If we have never set values for this field, we don't need a migration

**Comment by pallix** [comment]
Good. We can merge then.

**Pull request merged**
