### PR TITLE
Breaking: change meinberlin contexts

### PR DESCRIPTION
**Pull request by Johnschmidfront**
this is made possible by #2113.

so, as of now, contexts do not affect headers or templates in meinberlin anymore, **except** in Alexanderplatz.

### CODE REVIEW

**Comment by Johnschmidfront** [comment]
I noticed we don't check whether the process is in 'participate'. I'll add a check analogous to the one #2127. So that PR needs to be merged before this one.

**Comment by xi** [comment]
I don't think we should remove the contexts completely, (1) because it is a breaking change in the embed API which we would have to communicate to the embedders and (2) because these contexts still differs from the default one by not having user routes.

**Comment by xi** [comment]
Instead of not showing a button at all, all these cases had a deactivated version of the button.

**Comment by xi** [comment]
You removed the phase headers. I guess this was not intentional?

**Comment by Johnschmidfront** [comment]
unfortunately, we were a little too ambitious ... a slimmer PR will follow.

**Pull request closed without merging**
