### PR TITLE
automatic download external picture url

### PR DESCRIPTION
**Pull request by joka**
API changes:

- setting the `external_picture_url` field  triggers dowloadig the image url:
  The image is used to create an Image resource in the backend. 
  The old `picture` reference (if any) is removed an replaced with a refernce to the new image resource. 
  If you set both `external_picture_url` and the `picture` reference,  the custom reference is replaced by 
  the downloaded `external_picture_url` image.

### CODE REVIEW

**Comment by pallix** [comment]
I had some tests failing on this branch. I will retry once I manage to build A3 again.

**Comment by Johnschmidfront** [comment]
maybe I can help with this. what needs to be done in the frontend?

**Comment by pallix** [comment]
@joka test are failing

**Comment by joka** [comment]
all test pass on my local machine
I merged and rebased master

**Comment by joka** [comment]
Travis acceptance tests are faling due to database locking issues

**Comment by joka** [comment]
> maybe I can help with this. what needs to be done in the frontend?

Just note the api change ;)

**Comment by joka** [comment]
Travis test pass now except for spd, but I guess this is not due to this pull request.

**Comment by joka** [comment]
@pallix  can  you merge?

**Pull request merged**
