### PR TITLE
add support for requires.io

### PR DESCRIPTION
**Pull request by joka**
To list requirements go to:
 https://requires.io/github/liqd/adhocracy3/requirements/?branch=2016-06-jk-requirements

To update the requirement listing run: 
`bin/pip install  requires.io`
`bin/requires.io update-site -t a54831113b039e9edbb2d26c2d2f9a9c99887437 -r adhocracy3`

### CODE REVIEW

**Comment by xi** [comment]
- How can I get permissions to change settings on requires.io
- Is it possible to add frontend dependencies?

**Comment by 2e2a** [comment]
We probably should also add the usage example to documentation.

**Comment by joka** [comment]
> We probably should also add the usage example to documentation.

yes

**Comment by joka** [comment]
> How can I get permissions to change settings on requires.io

You have to login with you github account, but the only option is to revoke the authentication token.

> Is it possible to add frontend dependencies?

No, requires only reads buildout and pip requirements files.

**Comment by joka** [comment]
> We probably should also add the usage example to documentation.
> 
> yes

Do we want to add the authentication token to docs?

**Comment by 2e2a** [comment]
| Do we want to add the authentication token to docs?

Now its on github, so I think its ok to have it also in the docs. Not sure where we could put it otherwise.

**Comment by 2e2a** [comment]
lgtm

**Pull request merged**
