### PR TITLE
honey, I'm home

### PR DESCRIPTION
**Pull request by der-john**
This adds a `home` view that contains a process overview.

TODO (in separate PR):
- finalize styling
- document styling

### CODE REVIEW

**Comment by joka** [comment]
wie kommt man zum home view?

**Comment by der-john** [comment]
> wie kommt man zum home view?

Right now, the home view isn't accessible without typing it in the browser console yet.

In the near future, **if existent**, the home view will be accessible by doing one of the following:
- clicking on the logo on the top left corner (this is currently being implemented in PR #????),
- having yourself be redirected, e.g. after account activation (`redirect_url` in the config should be changed),
- probably: breadcrumbs in the process header saying "back to process overview".

**Comment by der-john** [comment]
in my opinion, the biggest problem right now is that I can't scroll on the `home` view.

**Comment by der-john** [comment]
ok. update:

- [x] scrollability
- [x] `collaborative_text` gets displayed (without pic !?)
- [ ] `stadtforum/poll` gets displayed

**Comment by der-john** [comment]
This is a good point in time for some rebasing.

**Pull request closed without merging**
