### PR TITLE
Relax AGPL license version

### PR DESCRIPTION
**Pull request by fisx**
See https://github.com/liqd/thentos/pull/393 for analogous thentos-PR, and https://github.com/liqd/thentos/issues/392 for the discussion.

TODO: You should check the first line of the new LICENSE.txt (2nd commit) and decide if that's a good slogan.  I was just making a wild guess.

### CODE REVIEW

**Comment by xi** [comment]
@nidico do you think this is possible? It seems like there are commits in the repo that are not "owned" by liqd, e.g. 325733da2ac62a57c81a79d4653d1fe433333362.

**Comment by nidico** [comment]
> It seems like there are commits in the repo

AFAIK the license change only applies to all files which are in the repository at the time of the license change (and afterwards). If contributors wouldn't agree to a license change, we could remove their code. But of course it's harder (though possible) to assemble a list of contributors whose contributions are still in the code.

> that are not "owned" by liqd

All contributors did their contributions either for liqd or for partou, and partially as voluntary work (by the same persons). So the safest would be to ask everybody who contributed code.

**Comment by joka** [comment]
What is still missing here,  should every developer  add add comment with  "yes i want this"?

**Comment by nidico** [comment]
> What is still missing here, should every developer add add comment with "yes i want this"?

This would be best.

@xi, @fisx, @local-girl, @pallix, @ChristianSi, @MagdaN, @mkind, @soenkehahn, @dwt, @slomo, @veryrandomname, @2e2a, @Johnschmidfront, @denisro, @fhartwig - do you all agree to changing the license to from AGPLv3 to "AGPLv3 *or any later version*"?

**Comment by nidico** [comment]
Btw: I agree to changing the license from AGPLv3 to "AGPLv3 or any later version".

**Comment by xi** [comment]
+1

**Comment by fisx** [comment]
> @xi, @fisx, @local-girl, @pallix, @ChristianSi, @MagdaN, @mkind, @soenkehahn, @dwt, @slomo, @veryrandomname, @2e2a, @Johnschmidfront, @denisro, @fhartwig - do you all agree to changing the license to from AGPLv3 to "AGPLv3 *or any later version*"?

yes, i do!

**Comment by fhartwig** [comment]
I agree to changing the license to from AGPLv3 to "AGPLv3 or any later version".

**Comment by mkind** [comment]
+1

**Comment by 2e2a** [comment]
+1

**Comment by pallix** [comment]
I'm fine with that.

**Comment by ChristianSi** [comment]
I agree, too.

**Comment by soenkehahn** [comment]
Yes, I agree.

**Comment by MagdaN** [comment]
I agree

**Comment by Johnschmidfront** [comment]
agree

**Comment by dwt** [comment]
Agreed.

**Comment by pra85** [comment]
Yes, I agree

**Comment by local-girl** [comment]
+1

**Comment by slomo** [comment]
I agree

**Comment by stadine** [comment]
+1

**Comment by slomo** [comment]
Since I lost track of who agreed and who didn't I collected again all developers from githubs contributers page.

- [x] xi
- [x] joka
- [x] fisx
- [x] localgrr
- [x] nidico
- [x] pallix
- [x] ChristianSi
- [x] MagdaN
- [x] der-john
- [x] mkind
- [x] soenkehahn
- [x] slomo
- [x] dwt
- [x] 2e2a
- [ ] @veryrandomname
- [ ] @denisro
- [x] fhartwig
- [x] stadine
- [x] pra85


https://guides.github.com/features/mastering-markdown/

**Comment by nidico** [comment]
> Does anyone has other means of contact to those contributors?

I'll contact @veryrandomname and @denisro.

**Comment by veryrandomname** [comment]
I agree

**Comment by joka** [comment]
Do we really have to wait for @denisro? His contribution is not part of the current code  for a long time.

**Comment by nidico** [comment]
I talked to @denisro and he's fine with the "upgrade".

**Comment by denisro** [comment]
On Thu, 26 May 2016 03:33:04 -0700
Nicolas Dietrich <notifications@github.com> wrote:

> > Does anyone has other means of contact to those contributors?  
> 
> I'll contact @veryrandomname and @denisro.
> 
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/liqd/adhocracy3/pull/1856#issuecomment-221836038

Hallo nochmal und Danke Dir!

<<<<< schnipp schnapp >>>>>

Was fuerne posse oder psychose? Ich lese kein
Adhocracy und muss da mal aktiv werden mit unsubscribe etc, stöhn. Sonst
habe ich ja auch noch telefon - klappt ja ;-). E-Mail und Internet sind
schon längere Zeit kaputt und werden deshalb von mir wie zu DDR-Zeiten
behandelt: also wenns denn sein muss und dann bitte ohne direkte,
relevante Meinungsäußerungen, Possen etc..

"Do we really have to wait for @denisro? His contribution is not part
of the current code  for a long time."

Meine KI antworted "approved, true". Da frage ich mich doch gegen: 
Kann ich diese Schmach, also meine "contribution" wieder loswerden? Mein
github-pw sollte abgespeichert sein.
Antwort: "not approved, possible true"

Gna, ich will jetzt nur nicht mehr bei joscha rumpöbeln und denke mir
meinen Teil ... naja possible false ... Kopf -> Tisch

Ja, ich habe viel Spass mit meinem neuen Berlin-Bild :-) Gerade eben
mit den Klempnern im Haus wieder sehr gelacht. Der Azubi hatte neulich
ein Bajonett ausm 1. WK im Fuss.

VG,
Denis

**Pull request merged**
