### PR TITLE
Prefix adhocracy scripts by "ad_"

### LINKED ISSUE #1504: prefix all adhocracy related scripts
In `bin/` there are third party tools like supervisor and buildout, but also some utility scripts that are part of adhocracy, e.g. assign_badges or import_bezirksregions. It is hard to see which of these tools belongs to which category. So I propose to prefix all adhocracy specific scripts with `a3_`.

This will probably have the biggest impact on deployment. The impact needs to be clear before this can be implemented.

### PR DESCRIPTION
**Pull request by pallix**
Prefix most of the scripts by `ad_`. See the commit message of the first commit for an explanation.

@slomo needs to adapt salt configuration.
@2e2a told me it's not a big deal.

@MagdaN @joka @xi if you see other scripts that I forgot and you want to prefix them, comment on this PR.

I think this PR was much needed given all the scripts we now have. Thanks @joka for the idea. 

Fix  #1504

### CODE REVIEW

**Comment by pallix** [comment]
@slomo maybe you can review the PR?

**Comment by xi** [comment]
Does this fix #1504?

**Comment by xi** [comment]
The frontend uses the prefix `adh` everywhere. I now it is much to ask to change al this again, but I would prefer if we could be consistent.

**Comment by joka** [comment]
Should we also change the name helpe scripts for developing to make them more visible?

sphinx_api_adhocracy
sphinx_build_adhocracy
make_wheels
check_code
remove_double_quotes_in_python_files
check_forbbiden_imports

**Comment by joka** [comment]
> The frontend uses the prefix adh everywhere. I now it is much to ask to change al this again, but I would prefer if we could be consistent.

What excatly is prefixed with adh?

The pull request is about using a prefix to have a better overview about our scripts. 
For me this does not have to be related to other prefixes we use.

**Comment by pallix** [comment]
I'm in favor of prefixing all our scripts

**Comment by pallix** [comment]
Ok done.

I'm assigning Yves for deployment :-)

**Comment by pallix** [comment]
`i18n` script is missing

**Comment by joka** [comment]
@pallix can you merge master?

**Comment by pallix** [comment]
I'm merging this every two days.

**Comment by pallix** [comment]
@slomo can we get this merged before I have to resolve conflicts for a third times?

**Comment by 2e2a** [comment]
@pallix You can merge, I'll adjust the deployment

**Comment by pallix** [comment]
Cool.

**Pull request merged**
