### PR TITLE
make bower dependencies more stable 

### PR DESCRIPTION
**Pull request by joka**
* update bower to 1.7.9		

* Force "https://" instead of "git://" to checkout git repositories

      - some proxies allow only http/https connection scheme (like my mobile network)
      - seems to make less connection problems when running bower recipe

* use revision number to checkout  socialsherprivacy/merriweather to allow caching

### CODE REVIEW

**Comment by joka** [comment]
failing acceptance tests

**Comment by joka** [comment]
failing jsunit tests

**Comment by slomo** [comment]
So what should we do about those failed test? Is this PR incomplete? Are those issues fixed on a new master version (looks like a backend issue to me)?

**Comment by joka** [comment]
> So what should we do about those failed test? Is this PR incomplete? Are those issues fixed on a new master version (looks like a backend issue to me)?

I guess its not related to this pull request. I have  similar failing test with my local master branch. But testing locally is quite usleses, on my machine the tests are failing for months now. 
I'm working on making the acceptance test more stable: https://github.com/liqd/adhocracy3/tree/2016-05-jk-update-protractor. We can wait for this, then I can verify  that the tests dont fail.

**Comment by xi** [comment]
The changes look good for me, espeically pinning commits is a great idea! I am not so sure about the git config, but I trust you if you say it is a good idea.

**Comment by slomo** [comment]
It think that a file in $REPO/.gitconfig is never read by git. According to [git-scm.org](https://git-scm.com/docs/git-config) only $REPO/.git/config and ~/.gitconfig are read. So I would drop that commit.

**Comment by der-john** [comment]
the protractor update has been merged. this PR works for me. @xi merge?

**Comment by joka** [comment]
> It think that a file in $REPO/.gitconfig is never read by git. According to git-scm.org only $REPO/.git/config and ~/.gitconfig are read. So I would drop that commit. Instead users should add this to their global gitconfig where it would also fix this for all other github related projects.

True 
Nevertheless i would prefere a solution without manual steps. Maybe set the git config with buildout, like the pre commit hook?

**Comment by xi** [comment]
I reverted 78486d5 and merged this otherwise uncontroversial pull request to get these improvements into master. @joka if you want to have a working solution for 78486d5, please open a separate pull request.

**Comment by joka** [comment]
> I reverted 78486d5 and merged this otherwise uncontroversial pull request to get these improvements into master. @joka if you want to have a working solution for 78486d5, please open a separate pull request.

#2346

**Pull request merged**
