### PR TITLE
2015 12 mn enable edit

### PR DESCRIPTION
**Pull request by MagdaN**

### CODE REVIEW

**Comment by local-girl** [comment]
Hi I made some progress tonight - mainly editing kind of works ! No console errors but there are some validation problems mainly I fixed Heard From checkboxes so they work in Edit but now not in create :-/ Actually I think I might have broken checkbox validation in general when moving this stuff to directive. I noticed when creating topics and heard from are not marked as required... Hopefully it's an easy fix cause I just have to leave right now, sorry.

**Comment by local-girl** [comment]
Also best to clean up the controller - lots of unused things in there now

**Comment by MagdaN** [comment]
At the moment this PR breaks the listing

**Comment by xi** [comment]
replaced by #1961

**Pull request closed without merging**
