### PR TITLE
refactor: use only colander schema for data validation, SRP

### PR DESCRIPTION
**Pull request by joka**
Internal Changes:

      - RestAPI view classes have no extra_validators hook anymore
        All validation has to happen in schemas defined in the class attributes schema_GET/POST/...

### CODE REVIEW

**Comment by pallix** [comment]
Acceptance test "cannot login with wrong password - fail" is failing. That's not good :-)

**Comment by joka** [comment]
> Acceptance test "cannot login with wrong password" is failing. That's not good :-)

we are just 'open'  software :)

**Comment by joka** [comment]
There is a failing python test on master (my fault, i did no proper pull request review)

**Comment by pallix** [comment]
All tests run locally for me

**Pull request merged**
