### PR TITLE
Store process start/end time in workflowassignment instead of processsettings

### PR DESCRIPTION
**Pull request by 2e2a**

### CODE REVIEW

**Comment by 2e2a** [comment]
Evolve script and frontend adjustments are still required.

**Comment by 2e2a** [comment]
As far as I understand there is only one element in the state_data array so far.
If not, we would need to get the correct index.

We could also discuss, why state_data has to be an array.

**Comment by xi** [comment]
You only changed the `IProcessSettings.participation_*`, right? The only place where this is used is in the frontend is `src/meinberlin/meinberlin/static/js/Packages/Meinberlin/Bplan/Process/Process.ts`.

**Comment by 2e2a** [comment]
@xi: Yes IProcessSettings.participation_ is removed and state_data in IWorkflowAssignment is used instead.

**Comment by 2e2a** [comment]
@pallix Fixed the state_data handling.

**Comment by pallix** [comment]
LGTM, migration still needed

**Comment by Johnschmidfront** [comment]
LGTM. @MagdaN could you review the frontend part please?

**Comment by MagdaN** [comment]
How can I test it?

**Comment by joka** [comment]
> how do we know that this information is at the first index?

This issue is not fixed yet, or?

**Comment by 2e2a** [comment]
>>how do we know that this information is at the first index?

>This issue is not fixed yet, or?

The should be fixed with the last commit. The state_data for 'participate' is used.

**Comment by xi** [comment]
When testing this locally with a fresh database, I received the following error on creating a proposal version:

    description: "KeyError: 'name'; time: 2016-02-22 15:05:51,564"
    location: "internal"
    name: ""

Could this be because I left the `name` field in the `IWorkflowAssignment` sheet blank? (see  d0039d6)

**Comment by 2e2a** [comment]
@pallix: Added migration

**Comment by pallix** [comment]
@xi will have a look at the error and then we can merge it

**Comment by xi** [comment]
I am waiting for @2099 as it seems to be related.

**Comment by xi** [comment]
I found a fix. Now it works for me.

**Comment by pallix** [comment]
This PR breaks the 100% test coverage.

@2e2a fixes it and then we can merge it.

**Comment by 2e2a** [comment]
@pallix: the test coverage is broken because if merging master

**Pull request merged**
