### PR TITLE
2016 01 cc fix topics other

### PR DESCRIPTION
**Pull request by local-girl**
requires #1946

### CODE REVIEW

**Comment by pallix** [comment]
Failed with this error

`src/mercator/mercator/build/js/Packages/Mercator/2016/Proposal/Proposal.ts(271,17): error TS2345: Argument of type '{ funding: null; explanation: null; }' is not assignable to parameter of type '{ funding: number; }'.
`

Can you try to merge master in the branch?

**Comment by pallix** [comment]
Ooops sorry I didn't want to closed, clicked on the wrong button :-)

**Comment by local-girl** [comment]
Oh dear thats my mistake I thought I reverted, get rid of the line explanation: null;

**Comment by local-girl** [comment]
Fixed with 483a883f6f02a191d5ac41a766993aecedd29c08

**Comment by MagdaN** [comment]
works

**Pull request merged**
