### PR TITLE
update lodash to 4.6.1

### PR DESCRIPTION
**Pull request by xi**
lodash 4.0.0 brought many breaking changes. This is why we did not update until now. I did not do extensive testing, but I thoroughly went through the breaking changes described in the [changelog](https://github.com/lodash/lodash/wiki/Changelog).

### CODE REVIEW

**Comment by xi** [comment]
I am still looking into the failing tests.

**Comment by xi** [comment]
The tests now pass locally. One test is still failing. See #2142 for that.

**Comment by Johnschmidfront** [comment]
I get one acceptance test failure - I assume it isn't related:
> user password reset error displayed if the email is not associated to an user
       Message:
         UnknownError: unknown error: Element is not clickable at point (525, 264). Other element would receive the click: <a class="login-cancel ng-binding" href="" data-ng-click="cancel()">...</a>
      (Session info: chrome=48.0.2564.116)
      (Driver info: chromedriver=2.15.322448 (52179c1b310fec1797c81ea9a20326839860b7d3),platform=Linux 4.2.0-30-generic x86_64)

Can somebody else test this please?

**Comment by Johnschmidfront** [comment]
Today, the above test passed. @xi says it's a common false negative.

**Comment by Johnschmidfront** [comment]
great.

**Pull request merged**
