### PR TITLE
try to stablize acceptance tests

### PR DESCRIPTION
**Pull request by joka**
After month of failing tests they pass now on my local machine. Th

* refactor: use jasmin2 async feature for send emails acceptance test			
* remove test backend without websocket server, not used			
* fix: acceptance tests do not cleanup the database / use supervisor test group
* increase backend server workers to slightly improve accptance test speed			
* add mercator test fixtures script			
* refactor: prefere beforeAll instead of beforeEach in acceptance tests  
* update protractor from 2.2 to 3.3 (breaking changes)  
* fix regression acceptance test (workaround with wait timeouts)			
* gardening protractor conf			
* fix: use same timeouts for proctractorConfSauce and protactorConfSauce			
* add pageload timeout for SauceLab config to make sure angular is loaded (this makes tests run much slower but it might help to preventing test  failures)

The acceptance test  refactoring make senses in general but its also needed to make the test run on my local machine after upgrading to protractor.

### CODE REVIEW

**Comment by slomo** [comment]
Looks very good, I have two questions:

 -  Is the increased number of workers still needed after adding the timeout? (I fear that out memory consumption becomes to big for travis)
 - Have you considered to wait for the comment content to be displayed after editing instead of adding a fixed timeout?

**Comment by joka** [comment]
> Looks very good,

sadly the travis tests are still failing.

 > I have two questions:

> Is the increased number of workers still needed after adding the timeout? (I fear that out memory consumption becomes to big for travis)

no, I suggest we reduce the workers for the frontend server to 2 (not much memory consumption) and the backend server back to 1 again.

> Have you considered to wait for the comment content to be displayed after editing instead of adding a fixed timeout?

that would be the proper solution. Debugging tests is still cumbersome for me and I did not want to spend more time.  I can fix this.

**Comment by slomo** [comment]
I cherry picked a few commits and created extra pull-requests from them:

https://github.com/liqd/adhocracy3/pull/2330/commits/d71db1b98fff9a9c3d7554bf1946b2817e266f50 -> #2350
https://github.com/liqd/adhocracy3/pull/2330/commits/c4a2be259ef46fc8dcb4d7ec59af7e14880bd55c https://github.com/liqd/adhocracy3/pull/2330/commits/2ef32a8ee6df5bea44e8a0e59a07a622e8a956d1 and more protractor config rebasing -> #2351
https://github.com/liqd/adhocracy3/pull/2330/commits/267353b565f1ef92bdac523f1e5b9665485dcd52 -> #2352

**Comment by joka** [comment]
> I cherry picked a few commits and created extra pull-requests from them:
> 
> d71db1b -> #2350
> c4a2be2 2ef32a8 and more protractor config rebasing -> #2351
> 267353b -> #2352

ok,  with the last commits the saucelab tests are getting greenish, so I'm still hopefull   with this pull request

**Comment by joka** [comment]
> Is the increased number of workers still needed after adding the timeout? (I fear that out memory consumption becomes to big for travis)
> no, I suggest we reduce the workers for the frontend server to 2 (not much memory consumption) and the backend server back to 1 again.

The travis sandbox has 3GB ram and two cores, that should be more then enough

**Comment by joka** [comment]
heureka, if you merge the new pull requests i can rebase this one.

**Comment by xi** [comment]
+1 for splitting this into smaller pull requests. I like many of the changes, but not all of them and it is hard to review this much at once.

**Comment by joka** [comment]
remaining commits moved to: 

https://github.com/liqd/adhocracy3/pull/2356 https://github.com/liqd/adhocracy3/pull/2355 https://github.com/liqd/adhocracy3/pull/2359

**Pull request closed without merging**
