### PR TITLE
Remove hardcoded meinberlin sample processes

### PR DESCRIPTION
**Pull request by 2e2a**
The bplan and kiezkasse sample processes are imported during the tests
from a resource file

### CODE REVIEW

**Comment by pallix** [comment]
Very nice.

Somehow the bplan is not listed in `http://localhost:6541/organisation/`. Is it still the case?

**Comment by pallix** [comment]
I mean, what is the case with the hardcoded version?

**Comment by 2e2a** [comment]
The hardcoded bplan example process was removed. Thus organisation is now empty and needs to be populated via import_resources.

**Comment by pallix** [comment]
Yes I understand, the problem ist that once imported, the bplan ist not listed within the organisation.

**Comment by 2e2a** [comment]
The bplan process is listed under organisation after the workflow is set to participate. This behavior is the same on the master branch.

**Comment by pallix** [comment]
Ok! maybe I had a cache problem.

**Pull request merged**
