### PR TITLE
Fix #2317  IGeoProposal creates IProposalVersion  as first version

### LINKED ISSUE #2317: IGeoProposalVersion gets converted to IProposalVersion
I am trying to get the `adhocracy_meinberlin.resources.idea_collection.IProcess` running locally by setting up the IdeaCollection workbench for it.

On the @create_proposal view, I provide title, description and a point, and click on submit.

The request header reads as follows (excerpt):
>1 {method: "POST", path: "@pn15",…}
body {content_type: "adhocracy_core.resources.proposal.IGeoProposalVersion",…}

The response preview reads as follows (excerpt):
> 1 {code: 200,…}
body: {path: "http://localhost:6541/organisation/idea_collection2/proposal_0000002/VERSION_0000000/",…}
content_type: "adhocracy_core.resources.proposal.IProposalVersion"

I am with my Latin at the end.

### PR DESCRIPTION
**Pull request by joka**
*  add correct item_type IGeoProposalVersion to resource metadata of IGeoProposal

### CODE REVIEW

**Comment by joka** [comment]
For Item we have two place to define the allowed resource types of children:

*  elements_types (like all pools) to define the addable resource types
* item_type (item only) to define the type of the first item version 

This is quite confusing, its easy to forget to set the item_type.

**Comment by der-john** [comment]
great! worked for me!

**Comment by joka** [comment]
merge if you need it

**Comment by der-john** [comment]
looks good. all tests pass.

**Pull request merged**
