### PR TITLE
 add comments_count  field  to ICommentable sheet

### PR DESCRIPTION
**Pull request by joka**
API Extensions:

- add field ICommentable:comment_count: 
 
  number of all comments referenced by ISubresource (IDocument/IMercator2Subresources) and       IComment references. Example traverse:
document -elements-> paragraph  <-referes_to- comment1 <-refers_to- comment2

  visiblity is checked but not view permissions

Internal Changes:

- refactor rate validation

- 'traverse' search comparator to so traveres all references of a given type starting by the given resource.

- 'send_reference_event' option for the sheet set method (defaults True) 
  (This is more like a workaround.  For testing I need to create References without raising IBacksheetAdded events. The exiting similar option 'send_event'  did not provided this, but fixing 
  this would be quite complicated)

Migration:

- short running migration script to set initial  'comment_count' field values

TODO: 

- [x]  Make the fronted use the new comment_count field for the Mercator2Proposal

### CODE REVIEW

**Comment by pallix** [comment]
LGTM for the backend part

**Comment by MagdaN** [comment]
@xi: could you check the FE part?

**Comment by xi** [comment]
FE seems to work fine. We could probably use the new API in many more places, but that can be done separately.

**Comment by pallix** [comment]
youhoo!

**Pull request merged**
