### PR TITLE
Fix resource path in auditlog

### PR DESCRIPTION
**Pull request by 2e2a**

### CODE REVIEW

**Comment by joka** [comment]
true, makes more sense
9 python tests are failing, is this related?

**Comment by 2e2a** [comment]
| 9 python tests are failing, is this related?

Tests for auditlog are passing. It looks like s1 tests are failing.

**Comment by joka** [comment]
> Tests for auditlog are passing. It looks like s1 tests are failing.

do you haven an idea why we did not notice this?

**Comment by 2e2a** [comment]
| do you haven an idea why we did not notice this?

No, I noticed this the first time running the tests for this pull request.

**Pull request merged**
