### PR TITLE
add prefix "api" to rest api url

### PR DESCRIPTION
**Pull request by joka**
API CHANGES:
- add prefix "api" to JSON REST API  URL to let the backend serve different kinds of data (JSON, HTML, SDI). This brakes the API for local development but not for productive installations, we just need to adapt the deployment settings for this update.

Internal Changes:
- make tests less depended of a specific API URL

### CODE REVIEW

**Comment by joka** [comment]
Why is this on hold,  no time to merge?

**Comment by 2e2a** [comment]
> Why is this on hold, no time to merge?

Yes. We will continue working on it when we have some more time.

**Comment by joka** [comment]
> Why is this on hold, no time to merge?
> Yes. We will continue working on it when we have some more time.

Can i do something?

**Comment by 2e2a** [comment]
Tried to test with the frontend:
* `etc/frontend_development.ini.in` needs to be adjusted
* Getting  `No 'Access-Control-Allow-Origin'` errors

**Comment by joka** [comment]
Fixed,  but at the moment my acceptance tests setup is broken, so I cannot test them.

**Comment by joka** [comment]
Acceptance tests pass now.

**Pull request merged**
