### PR TITLE
update pytest

### PR DESCRIPTION
**Pull request by joka**
* update py.test from 2.8 to 2.9
  less noise on travis with --color option (https://github.com/pytest-dev/pytest/issues/1397)

* cleanup remove pytest-pyramid
  not used

### CODE REVIEW

**Comment by joka** [comment]
there is a pytest failing on travis

**Comment by xi** [comment]
I noticed some pytests failing also in other branches. I will check if this is specific to this branch.

**Comment by xi** [comment]
I can reproduce the failing test locally. @joka can you please look into it?

**Comment by joka** [comment]
The last commit fixed the issue, regression caused by #2355

**Comment by joka** [comment]
now only the acceptance test are failing, but this is not related to this pull request.

**Pull request merged**
