### PR TITLE
[Breaking] make redirect url configurable

### PR DESCRIPTION
**Pull request by Johnschmidfront**
Until now, the "redirect URL" - where you are redirected e.g. when you
load the page - has been hard-coded in each project's Adhocracy.ts. Now
it is a configuration variable that is given a value in each project's
buildout.cfg, and passed on to frontend_development.ini.in ->
__init__.py --> config.ts (JSON) --> Adhocracy.ts.

### CODE REVIEW

**Comment by xi** [comment]
Fixes #1640

**Comment by slomo** [comment]
Nice :+1:

**Comment by pallix** [comment]
Nice :+1:

**Comment by xi** [comment]
Ready for merge. @slomo and @2e2a: Merge whenever you want to.

**Pull request merged**
