### PR TITLE
forum of forums

### PR DESCRIPTION
**Pull request by der-john**
This roughly adds the logic needed to provide `stadtforum` poll listings outside embedded contexts.

*Warning:* The layout is still suboptimal and the logic may be insufficient.

To do:
- [ ] improve layout
- [ ] add i18n for polls (after #2732 is merged)
- [ ] make create and edit work

### CODE REVIEW

**Comment by der-john** [comment]
Ceterum censeo: `Stadtforum` should be integrated into `IdeaCollection` some time.

**Comment by der-john** [comment]
There are some incompatibilites with `master` due to #2747.

**Comment by der-john** [comment]
> There are some incompatibilites with master due to #2747.

solved.

**Comment by xi** [comment]
This is a great step forward (though not ready for production use)

**Pull request merged**
