### PR TITLE
by default don't list elements of IServicePool (performance workaround)

### PR DESCRIPTION
**Pull request by joka**
API Change

- IServie pool like (../comments, ..../rates, ../users/ don't list elements by default.
 Instead the elements count is shown. If you need all resources do a search query, 
 and limit search results, for example with .` ../comments/?serialization_form=content&limit=10`

Part of https://github.com/liqd/adhocracy3/issues/1932, 
Assumes: https://github.com/liqd/adhocracy3/pull/1958 is merged.

### CODE REVIEW

**Comment by pallix** [comment]
LGTM. Can you document it in the REST API document since it impact the API?

**Comment by pallix** [comment]
@xi or @MagdaN will proof manually that the frontend does not break

**Comment by xi** [comment]
I did not have the time to look at this in detail, but it seems to be introduce major inconsitency into our API. I would really prefer to fix this in the frontend (I have some ideas how this could work)

**Comment by joka** [comment]
> I did not have the time to look at this in detail, but it seems to be introduce major inconsitency into our API. I would really prefer to fix this in the frontend (I have some ideas how this could work)

This improves alot performance with the exinting frontend and and other clients that might do get request to our backend. On the ohter hand it does not brake anything and its documented .
Regarding "inconsitency"  i don't thing its worse that the current state of the API.
Improving the frontend is also possible but we have more important  issues at the moment.

For a proper solution for listiing large numbers of references i suggested we find a solution based on the json/hydra API standard.

**Comment by xi** [comment]
I talked to @joka and here is what we came up with: The solution proposed here should be extended to all pools. This way the API does not loose consistency. The frontend does not use the IPool sheet a lot so there is no huge amount of adaption needed. And the performance improvement is even bigger because it applies to more cases.

Closing this PR in favor of the new concept.

**Pull request closed without merging**
