### PR TITLE
update protractor to next major release 4

### PR DESCRIPTION
**Pull request by joka**
Manual update steps needed:

- `bin/buildout`
- `bin/webdriver-manager update`
- make sure google-chrome version >= 53

### CODE REVIEW

**Comment by xi** [comment]
meinberlin failed on travis with the following error:

```
[14:32:39] E/launcher - Timed out waiting for the WebDriver server at http://127.0.0.1:41436/hub
[14:32:39] E/launcher - Error: Timed out waiting for the WebDriver server at http://127.0.0.1:41436/hub
```

We need to inverstigate this before merging

**Comment by joka** [comment]
mercator build passes
but spd also fails::

    1) ratings is not affected by the edition of the comment
        Message: Failed: No element found using locator: By(css selector, .listing-create-form)

I dont know if these are normal random travis failures or something new.

**Comment by joka** [comment]
I don't understand the the main berlin error, we use "direct connect"  with firefox and not the webdriver server.
The spd error is a common one: https://travis-ci.org/liqd/adhocracy3/jobs/175677938 meinberlin

I guess the testing situation is not getting worse with this pull request.

**Comment by xi** [comment]
I found another issue: Running tests locally with firefox works fine, but chrome (53.0.2785.143) does not work at all.

**Comment by 2e2a** [comment]
On master the protractor tests run with chromium  54.0.2840.100  terminate immediately after opening the browser. On this branch the tests also terminate unsuccessfully, but after executing some tests.

**Comment by joka** [comment]
local tests (with buildout-s1.cfg) and  chrome 54 are running fine on my machine
( But after downgrading  and rerunning "bin/webdriver-manager update" they terminate immediatly)

**Comment by joka** [comment]
chrome 54 and firefox are working fine now on my local machine.
@2e2a what was your error message?

**Comment by 2e2a** [comment]
> @2e2a what was your error message?

Tested once again. Now protractor works with chromium, but two tests fail. With firefox (49.0.2) still nothing happens and the test terminates with a timeout.

**Comment by joka** [comment]
> Tested once again. Now protractor works with chromium, but two tests fail. With firefox (49.0.2) still nothing happens and the test terminates with a timeout.

This cannot be a general issue, i have the exact same firefox version.
The main thing is that the travis test run at least as "good" as before.
Regarding the local test runs are worse or better i cannot say. At least for me its better (tests work with fresh started system and google chrome 54.0.2840.100 and firefox 49.0.2,  did not have working tests before).

So I don't know what we should do with this pull request:

- improve / investigate something
- just merge it
- don't merge it at all due to strange problems with local testing

**Comment by 2e2a** [comment]
> So I don't know what we should do with this pull request:

I would suggest to just merge it, as after the webdriver-manager update the test do not work on master too.

**Pull request merged**
