### PR TITLE
Fix sources for pep8

### PR DESCRIPTION
**Pull request by pallix**

### CODE REVIEW

**Comment by xi** [comment]
The `__init__.py` files are generated from `src/adhocracy_frontend/adhocracy_frontend/scaffolds/adhocracy/+package+/__init__.py_tmpl`. So the issue should be fixed there, too.

The `version.py` is third party code and should probably be excluded from linting.

**Comment by pallix** [comment]
Should we exclude `version.py` from the linter or it is sometimes modified manually?

**Comment by joka** [comment]
> Should we exclude version.py from the linter or it is sometimes modified manually?

version.py passed the pep8 test, so why should we exclude it?

**Comment by xi** [comment]
> > Should we exclude version.py from the linter or it is sometimes modified manually?
>
> version.py passed the pep8 test, so why should we exclude it?

It did *not* pass the pep8 test (this is what this PR is about) and it is third party code. We should not modify that code so there is no need to lint it.

**Comment by joka** [comment]
> It did not pass the pep8 test (this is what this PR is about) and it is third party code. 
anyway, if its easy fix we should do it, then we don't depend on special configuration to make the pep8 test pass.

**Comment by joka** [comment]
lgtm

**Comment by joka** [comment]
> Should we exclude version.py from the linter or it is sometimes modified manually?

It was modified twice until  now.

**Pull request merged**
