### PR TITLE
Simplify check code and compile

### PR DESCRIPTION
**Pull request by slomo**
- delete all symlinks in target dir upon start
 - fixes error with moved or delted files in any source dir

### CODE REVIEW

**Comment by xi** [comment]
If we delete a symlink to a .ts file, is it possible to also delete the compiled .js file? I feel like the residual .js files tend to cause trouble.

**Comment by slomo** [comment]
Well I can pull the atomic option and delete the entire target directory. It would also be even simpler.

**Comment by slomo** [comment]
I reevaluated that, and it seems that I can't simply delete the target dir. Also it would be a bit strange to add a special case for a subset of js files (only those in /js) in this rather generic script. So how urgent is this issue?

**Comment by xi** [comment]
I am not completely sure how urgent this is. In the past few weeks thetre were some issues after moving or deleting typescripot code. I suspect that this was caused by residual js files, but I did not really investigate.

**Comment by slomo** [comment]
Maybe those are the same error, that are already fixed by this change: Errors with stale links, and therefore non readable typescript files.

**Comment by xi** [comment]
LGMT

**Pull request merged**
