### PR TITLE
remap icons

### LINKED ISSUE #2646: IE11 doesn't always render our icon font
Sadly we have no Idea what exact set of preconditions trigger this bug. We cannot reproduce it on our boxes, but we saw it on all machines  at Stendal.

Some screenshots that show the problem are appended.

My analysis: something prevents the custom icon font from loading / showing in some configurations of windows.

Some common reasons would be that external font loading is disabled completely, or in the browser. However, we know that the previous deployment of S1 had working icons. So either they changed that setting recently, or we changed something about how we deploy that font file.
image1
50929cd6-6ba1-11e6-8909-a0455f96aa15
image3
image4
image5
image6

### PR DESCRIPTION
**Pull request by xi**
Fixes #2646; Replaces #2760 

This uses `.fontcustom-manifest.json` to define custom unicode codepoints for icons. This way the system fonts can display a reasonable fallback if the iconfont cannot be loaded.

Note that #2760 also removed some unnecessary icons. I did not include that in my pull request because I did not have the time. This should still be done in a separate pull request.

### CODE REVIEW

**Comment by der-john** [comment]
I tried to test this with uBlock and got
> GET http://localhost:6551/static/js/Packages/Core/Tracking/Tracking.js net::ERR_BLOCKED_BY_CLIENT

**Comment by der-john** [comment]
I'm having problems testing this.

**Comment by der-john** [comment]
To do:
- [ ] rebuild demo font
- [ ] rebuild mercator font
- [ ] rebuild euth font
- [ ] rebuild pcompass font

**Comment by xi** [comment]
IMHO we do not need to rebuild the other fonts now. This feature is nice, but only really required for s1.

**Comment by der-john** [comment]
works.

**Pull request merged**
