### PR TITLE
show results in resultsphase also to anonymous user

### PR DESCRIPTION
**Pull request by MagdaN**
does not work yet (at least with my test data).

### CODE REVIEW

**Comment by MagdaN** [comment]
I tried to get this working, but apparently  adhHttp.get(processUrl) is undefined. It seems to me that currentSpace in adhToplevelstate is not set.

**Comment by xi** [comment]
Should work now.

**Comment by MagdaN** [comment]
Works!

**Comment by xi** [comment]
> if users are not logged in, we don't know which part is supposed to be red and which one is grey.

fixed

**Pull request merged**
