### PR TITLE
Use local firefox with xvfb instead of sauce labs

### PR DESCRIPTION
**Pull request by slomo**
More effecting integration testing on travis.

### CODE REVIEW

**Comment by xi** [comment]
I think there were reasons why we postponed updating protractor in the past. Do you know about them and if yes, what changed?

**Comment by xi** [comment]
Could you give a brief overview of pros/cons? I guess this is faster (about 20%) and less vulnerable to network timeouts. Anything else?

**Comment by slomo** [comment]
I dont' know why we didn't update protractor. It is though required for this pull-request because the old version seems to have some issues with the firefox driver and the chrome version on travis is currently to old to run with either the new or the old chrome driver.

**Comment by slomo** [comment]
My main motivation was speed. It makes the test setup more similar to the local one and remove dependency to sauce labs as an external service (though increasing coupling with travis a bit more). A big downside is that we can't run tests with other browsers any more (which we weren't doing any more). An other downside is that this might bring us closer to the travis memory limit, which when violating it leads to hard to debug test aborts.

**Comment by slomo** [comment]
I have spoken with @der-john, he didn't update protractor the last time because there were some tests failing afterwards. But this was either a protractor issue or unrelated because now everything keeps working.

**Comment by slomo** [comment]
Rebased on to master an squashed all dummy commits. Some change here are conflicting with #2330.

**Comment by xi** [comment]
Continued in #2353

**Pull request closed without merging**
