### PR TITLE
Allow s1 participants to renominate proposals

### LINKED ISSUE #2739: S1: Renominate broken for normal users
It does work for admins though.

To reproduce:
* Visit https://aastendal-stage.partou.org/manage/
* Create a user, with the group 'participants-aastendal'
* Login with that user
* Go to 'archive'
* Select a proposal that has **NOT** won
* Click the renominate button that is visible (it won't show for proposals that have been accepted already)
* A dialog box should show up telling the user that the page will reload is shown
* that reload does not happen
* the proposal is also not renominated.

It does work as admin though.

The JS console also shows these errors:
```
[Error] Array (1)
0 Object

code: 400

description: "Unrecognized keys in mapping: \"{'adhocracy_core.sheets.workflow.IWorkflowAssignment': {'workflow_state': 'proposed'}}\""

location: "body"

name: "data"

Object Prototyp

Array Prototyp

	(anonyme Funktion) (angular.min.js:90:234)
	(anonyme Funktion) (angular.min.js:131:105)
	$digest (angular.min.js:142:426)
	$apply (angular.min.js:146:121)
	l (angular.min.js:97:329)
	J (angular.min.js:102)
	onload (angular.min.js:103)
```

### PR DESCRIPTION
**Pull request by 2e2a**
Fixes #2739 

For testing it is important that renominate works for a proposal created by another user.

### CODE REVIEW

**Comment by der-john** [comment]
looks great. I'd love to test it - but somehow my default `s1` process has disappeared...

**Comment by der-john** [comment]
I made a `resources.json` for S1, but now I can't change the phase of the process:

> "/principals/users/0000000" is not one of group:default_group, group:gods

**Comment by 2e2a** [comment]
> I made a resources.json for S1, but now I can't change the phase of the process:


The problem should be fixed via #2725. This has now been merged here, so please retry.

**Comment by der-john** [comment]
works, too.

**Pull request merged**
