### PR TITLE
Remove unused sheet fields: comments

### PR DESCRIPTION
**Pull request by pallix**
Workaround to improve performance. This pull request is part of issue #1932

API CHANGE:

- rm field: ICommentable:comments

TODO:

- [x]  frontend: all commentables should uses the provided comment_count field, see #1958
   (IDocument, IProposal, IParagraph,  mercator/meinberlin/spd proposal resources)

### CODE REVIEW

**Comment by pallix** [comment]
@joka is going to provide a `comments_count` field for the sheet

**Comment by joka** [comment]
> @joka is going to provide a comments_count field for the sheet. This will avoid listing the comments for nothing via the REST API as it is done currently by the frontend, since the list of comments was always returned via the sheet.

see https://github.com/liqd/adhocracy3/pull/1958

**Comment by joka** [comment]
This pull request is part of  issue https://github.com/liqd/adhocracy3/pull/1958

**Comment by joka** [comment]
LGTM

**Comment by pallix** [comment]
Can be merged once frontend is adapted for #1958

**Comment by pallix** [comment]
@xi @MagdaN frontend still needs adaptation, even after  #1958 merged

**Comment by joka** [comment]
I disabled rates field on mercator production to ocassional failing search requests (sorty by rates)

**Comment by pallix** [comment]
Joscha schreibt:

"  Vor dem finalen relasen sollten wir noch
       https://github.com/liqd/adhocracy3/pull/1957
       mergen, es kann sonst be Suchanfragen zu Fehlern kommen weil sie zu lange
       dauern.
" 
@xi @MagdaN

**Comment by xi** [comment]
If I understand correctly backreferences are not needed because you can go to the `post_pool` instead and filter by e.g. `object` (for rates). What is the name of the corresponding index for comments (and does it already exist)?

In the frontend, this is what is already done for rates, so this part does not need any adaption. It is very different for comments however. So I propose to split this pull request and only merge the rate part right now.

**Comment by pallix** [comment]
You can search for `content_type=adhocracy_core.resources.comment.ICommentVersion&tag=LAST`

**Comment by joka** [comment]
added pull request  https://github.com/liqd/adhocracy3/pull/2014

**Comment by joka** [comment]
@xi @Johnschmidfront   you still use the comments field  https://github.com/liqd/adhocracy3/blob/fe33e3be3066c3c9e9e02b79214293ca3cfe921e/src/adhocracy_frontend/adhocracy_frontend/static/js/Packages/Comment/Adapter.ts#L92

Are you still working on this or can we merge this?

**Comment by xi** [comment]
I would like to change the frontend in order to allow this, but I am not sure when this will happen. It could take anything from one day to few weeks.

**Comment by xi** [comment]
After merging #2053 the frontend does not use `ICommentable.comments` anymore.

**Pull request merged**
