### PR TITLE
Add user export script for mercator 2016

### PR DESCRIPTION
**Pull request by 2e2a**

### CODE REVIEW

**Comment by 2e2a** [comment]
@pallix , @joka: Can be merged

**Comment by pallix** [comment]
The export script 2016 is a copy/paste no? It would be better to refactor the code.

**Comment by 2e2a** [comment]
@pallix: Yes its copy/paste, but I'm not sure if refactoring such one-time scripts is worth the effort

**Comment by joka** [comment]
> @pallix: Yes its copy/paste, but I'm not sure if refactoring such one-time scripts is worth the effort

Next year we will need a similar script again, so its not really  a one time script.
To avoid code bloat I would use the same module (mercator_export_users), reuse helper methods and extend get_most_rated_proposals to work with different types of MercatorProposal.

**Comment by 2e2a** [comment]
> >@pallix: Yes its copy/paste, but I'm not sure if refactoring such one-time scripts is worth the effort

>Next year we will need a similar script again, so its not really a one time script.
>To avoid code bloat I would use the same module (mercator_export_users), reuse helper >methods and extend get_most_rated_proposals to work with different types of >MercatorProposal.

For the other scripts we did a copy for 2016 proposals instead of having the same script handling both resources.
Do we need to decide how to handle this in general to have a consistent scripts structure? Or just do it different for this script?

**Comment by 2e2a** [comment]
Moved common functionality into  a single script.

**Pull request merged**
