### PR TITLE
Fix INSTALLATION: prefer virtualenv rather than compiling python

### PR DESCRIPTION
**Pull request by nidico**
This is what everybody does already anyway, so it's really a fix, not a change.

### CODE REVIEW

**Comment by dwt** [comment]
Looks good from my side - and it's what I did too anyway.

**Comment by pallix** [comment]
LGTM

**Comment by pallix** [comment]
I also have success with pyenv.

**Comment by joka** [comment]
> I also have success with pyenv.

I would also prefere pyvenv, its good to use the "standard" way  python provides to do things

**Comment by joka** [comment]
Can we close the taiga ticket regarding the same issue now? https://tree.taiga.io/project/a3/us/624

**Comment by nidico** [comment]
> Can we close the taiga ticket regarding the same issue now?

Yes, done.

**Comment by nidico** [comment]
> I would also prefere pyvenv, its good to use the "standard" way python provides to do things

Feel free to submit a PR, I agree pyvenv is better nowadays, I just forgot about it when I wrote the text.

**Comment by xi** [comment]
> Can we close the taiga ticket regarding the same issue now? https://tree.taiga.io/project/a3/us/624
@xi I guess you created the taiga ticket

I did not create the ticket, so I don't mind if you close it.

**Pull request merged**
